language: python
python:
  - "3.7"
dist: xenial
install:
  - pip install pipenv
  - pipenv install --dev --ignore-pipfile .
script:
  - pytest --cov=.
after_success:
  - bash <(curl -s https://codecov.io/bash)
